CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE person (
    id_person integer GENERATED BY DEFAULT AS IDENTITY,
    nama text,
    password text,
    CONSTRAINT "PK_person" PRIMARY KEY (id_person)
);

CREATE TABLE toko (
    id_toko integer GENERATED BY DEFAULT AS IDENTITY,
    nama_toko text NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    CONSTRAINT "PK_toko" PRIMARY KEY (id_toko)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250602031736_InitToko', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE "Products" (
    "Id_Product" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nama_Product" text NOT NULL,
    "Harga" integer NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id_Product")
);

CREATE TABLE "Proyeks" (
    "Id_Proyek" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nama" text NOT NULL,
    "IsSelesai" boolean NOT NULL,
    CONSTRAINT "PK_Proyeks" PRIMARY KEY ("Id_Proyek")
);

CREATE TABLE "ProyekProducts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProyekId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Jumlah" integer NOT NULL,
    CONSTRAINT "PK_ProyekProducts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProyekProducts_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id_Product") ON DELETE CASCADE,
    CONSTRAINT "FK_ProyekProducts_Proyeks_ProyekId" FOREIGN KEY ("ProyekId") REFERENCES "Proyeks" ("Id_Proyek") ON DELETE CASCADE
);

CREATE INDEX "IX_ProyekProducts_ProductId" ON "ProyekProducts" ("ProductId");

CREATE INDEX "IX_ProyekProducts_ProyekId" ON "ProyekProducts" ("ProyekId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250603205151_InitialCreate', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250603205635_InitProyek', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250603211455_CreateProyekProductTable', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "ProyekProducts" DROP CONSTRAINT "FK_ProyekProducts_Products_ProductId";

ALTER TABLE "ProyekProducts" DROP CONSTRAINT "FK_ProyekProducts_Proyeks_ProyekId";

ALTER TABLE "Proyeks" DROP CONSTRAINT "PK_Proyeks";

ALTER TABLE "ProyekProducts" DROP CONSTRAINT "PK_ProyekProducts";

ALTER TABLE "Products" DROP CONSTRAINT "PK_Products";

ALTER TABLE "Proyeks" RENAME TO proyek;

ALTER TABLE "ProyekProducts" RENAME TO proyekproduct;

ALTER TABLE "Products" RENAME TO product;

ALTER TABLE proyek RENAME COLUMN "Nama" TO nama;

ALTER TABLE proyek RENAME COLUMN "Id_Proyek" TO id_proyek;

ALTER TABLE proyek RENAME COLUMN "IsSelesai" TO is_selesai;

ALTER TABLE proyekproduct RENAME COLUMN "Jumlah" TO jumlah;

ALTER TABLE proyekproduct RENAME COLUMN "Id" TO id;

ALTER TABLE proyekproduct RENAME COLUMN "ProyekId" TO proyek_id;

ALTER TABLE proyekproduct RENAME COLUMN "ProductId" TO product_id;

ALTER INDEX "IX_ProyekProducts_ProyekId" RENAME TO "IX_proyekproduct_proyek_id";

ALTER INDEX "IX_ProyekProducts_ProductId" RENAME TO "IX_proyekproduct_product_id";

ALTER TABLE product RENAME COLUMN "Nama_Product" TO nama_product;

ALTER TABLE product RENAME COLUMN "Harga" TO harga;

ALTER TABLE product RENAME COLUMN "Id_Product" TO id_product;

ALTER TABLE product ADD satuan text NOT NULL DEFAULT '';

ALTER TABLE proyek ADD CONSTRAINT "PK_proyek" PRIMARY KEY (id_proyek);

ALTER TABLE proyekproduct ADD CONSTRAINT "PK_proyekproduct" PRIMARY KEY (id);

ALTER TABLE product ADD CONSTRAINT "PK_product" PRIMARY KEY (id_product);

ALTER TABLE proyekproduct ADD CONSTRAINT "FK_proyekproduct_product_product_id" FOREIGN KEY (product_id) REFERENCES product (id_product) ON DELETE CASCADE;

ALTER TABLE proyekproduct ADD CONSTRAINT "FK_proyekproduct_proyek_proyek_id" FOREIGN KEY (proyek_id) REFERENCES proyek (id_proyek) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250607141903_TambahKolomSatuanDiProduct', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE product DROP COLUMN satuan;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250607175115_AddSatuanToProduc', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE product ADD satuan text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250607183458_TambahKolomSatuan', '8.0.0');

COMMIT;

